trigger:
- main

pr:
  branches:
    include:
    - '*'

schedules:
- cron: "0 0 * * *"
  displayName: Nightly build
  branches:
    include:
    - main
  always: "true"

jobs:
  - template: .azure-pipelines/linux.yml
    parameters:
      name: Linux
  - template: .azure-pipelines/windows.yml
    parameters:
      name: Windows
