trigger:
- main

pr:
  branches:
    include:
    - '*'

jobs:
  - template: .azure-pipelines/linux.yml
    parameters:
      name: Linux
  - template: .azure-pipelines/windows.yml
    parameters:
      name: Windows
