parameters:
  name: 'Windows'

jobs:
- job: ${{ parameters.name }}

  pool:
    vmImage: windows-latest

  # Test multiple versions of python.
  strategy:
    matrix:
      DefaultPython:
        # Currently 3.9
        conda_env: 'mlos_core'
        PythonVersion: ''
  # Python 3.6 is currently incompatible.
  #   Python36:
  #     conda_env: 'mlos_core-3.6'
  #     PythonVersion: '3.6'
  # Skipping testing of additional versions on Windows for now.
  #    Python38:
  #      conda_env: 'mlos_core-3.8'
  #     PythonVersion: '3.8'
  #    Python39:
  #      conda_env: 'mlos_core-3.9'
  #     PythonVersion: '3.9'

  variables:
    - name: CONDA_CACHE_DIR
      value: $(CONDA)/envs/$(conda_env)
      #value: $(CONDA)/envs
    - name: cache_cur_date
      value: "0000-00-00"
    - name: cache_cur_hour
      value: "00"
    - name: cache_prev_hour
      value: "23"

  steps:
  - pwsh: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - pwsh: |
      Write-Host "##vso[task.setvariable variable=cache_cur_date;]" (Get-Date -Format yyyy-MM-dd)
      Write-Host "##vso[task.setvariable variable=cache_cur_hour;]" (Get-Date -Format HH)
      Write-Host "##vso[task.setvariable variable=cache_prev_hour;]" (Get-Date).AddHours(-1).ToString('HH')
    displayName: 'Set cache timestamp variables'
  - pwsh: |
      echo "cache_cur_date: $(cache_cur_date)"
      echo "cache_cur_hour: $(cache_cur_hour)"
      echo "cache_prev_hour: $(cache_prev_hour)"
      echo "CONDA_CACHE_DIR: $(CONDA_CACHE_DIR)"
    displayName: 'Print some pipeline variables'
  - task: Cache@2
    displayName: Restore cached conda environment
    inputs:
      key: 'conda | "$(Agent.OS)" | "$(conda_env)" | conda-envs/$(conda_env).yml | mlos_core/setup.py | mlos_bench/setup.py | "$(cache_cur_date)" | "$(cache_cur_hour)" | azure-pipelines.yml | .azure-pipelines/windows.yml'
      path: $(CONDA_CACHE_DIR)
      # Prefer cached environments from the last hour or day.
      restoreKeys: |
        conda | "$(Agent.OS)" | "$(conda_env)" | conda-envs/$(conda_env).yml | mlos_core/setup.py | mlos_bench/setup.py | "$(cache_cur_date)" | "$(cache_cur_hour)"
        conda | "$(Agent.OS)" | "$(conda_env)" | conda-envs/$(conda_env).yml | mlos_core/setup.py | mlos_bench/setup.py | "$(cache_cur_date)" | "$(cache_prev_hour)"
  #     conda | "$(Agent.OS)" | "$(conda_env)" | conda-envs/$(conda_env).yml | mlos_core/setup.py | mlos_bench/setup.py | "$(cache_cur_date)"
      cacheHitVar: CONDA_CACHE_RESTORED

  # NOTE: these steps are handled by the Makefile in Linux environments for reusability.

  - pwsh: |
      conda config --set channel_priority strict
      #conda update -v -y -n base conda
    displayName: Update and configure conda

  # Try and speed up the pipeline by using a faster solver:
  # Nevermind, seems to be broken in ADO Windows runners atm :'(
  #- pwsh: |
  #    conda install -v -y -n base conda-libmamba-solver
  #    conda config --set experimental_solver libmamba
  #  displayName: Install and default to experimental mamba solver

  - pwsh: |
      if (! (conda env list | Select-String -Pattern "^$(conda_env) ") ) { conda env create -v -n $(conda_env) -f conda-envs/$(conda_env).yml }
      conda env update -v -n $(conda_env) -f conda-envs/$(conda_env).yml --prune
    displayName: 'Create/update mlos_core conda environment'

  - pwsh: conda run -n $(conda_env) pip install pytest-azurepipelines
    displayName: 'Install pytest-azurepipelines'

  - pwsh: conda run -n $(conda_env) pylint -j0 mlos_core/mlos_core mlos_bench/mlos_bench
    displayName: 'Run lint checks'
  - pwsh: |
      $env:PYTHONPATH="${PWD};${env:PYTHONPATH}"
      conda run -n $(conda_env) pytest mlos_core/ mlos_bench/
    displayName: 'Run tests'

  # Note: unlike the Makefile version, the pwsh version of these rules are all run within a single shell context, so we can
  # split commands across lines with CWD maintained (hence we also require the "cd .." here).
  - pwsh: |
      # Build the mlos_core wheel.
      cd mlos_core
      conda run -n $(conda_env) python setup.py bdist_wheel
      cd ..
      $mlos_core_whl = (Resolve-Path mlos_core/dist/mlos_core-*-py3-none-any.whl | Select-Object -ExpandProperty Path)
      echo $mlos_core_whl
      # Build the mlos_bench wheel.
      cd mlos_bench
      conda run -n $(conda_env) python setup.py bdist_wheel
      cd ..
      $mlos_bench_whl = (Resolve-Path mlos_bench/dist/mlos_bench-*-py3-none-any.whl | Select-Object -ExpandProperty Path)
      echo $mlos_bench_whl
      # Setup a clean environment to test installing/using them.
      conda create -y -v -n mlos-dist-test-$(PythonVersion) python=$(PythonVersion)
      conda install -y -v -n mlos-dist-test-$(PythonVersion) pytest
      conda install -y -v -n mlos-dist-test-$(PythonVersion) conda-forge::gpy
      conda run -n mlos-dist-test-$(PythonVersion) pip install -r test-requirements.txt
      # Install mlos_core wheel.
      conda run -n mlos-dist-test-$(PythonVersion) pip install $mlos_core_whl
      # Install mlos_bench wheel.
      conda run -n mlos-dist-test-$(PythonVersion) pip install $mlos_bench_whl
      # Just pick one simple test to run for now.
      # The rest should have been handled in a separate step.
      conda run -n mlos-dist-test-$(PythonVersion) python -m pytest mlos_core/mlos_core/spaces/tests/spaces_test.py
      # Run a simple mlos_bench test.
      conda run -n mlos-dist-test-$(PythonVersion) python -m pytest mlos_bench/mlos_bench/environment/azure/tests/azure_services_test.py
    displayName: 'Generate and test binary distribution files'
